### PR TITLE
Use "natbib" style

### PR DESCRIPTION
**Pull request by samm82**
While this doesn't exactly use `natbib`, which is a different package than `biblatex`, this change seems to accomplish the desired result of having citations be referenced by an "ID" with the author name(s) and year. Is this what you were expecting?

~~Closes # 7~~ Replaced by #17

### CODE REVIEW

**Comment by smiths** [comment]
@samm82, why not use natbib (`\usepackage[round]{natbib}`)?  The style you have used doesn't have the same results in the pdf.  The natbib style would show (Crawford and Carette, 2023), not CC23.  It is nice to name the bibtex label using the same natbib style (CrawfordAndCarette2023, for example).  The nice things about the natbib style is that the reader doesn't have to guess the names of the authors.  They are right there in the citation.

**Comment by samm82** [comment]
Thanks for the clarification! I had seen this style used by one of the textbooks lent to me, so I second-guessed what you wanted, especially since it used a different package than Jason's template. In hindsight, neither reason is enough to warrant not using the specific package you had suggested, and I definitely see the usefulness of it.😅 Glad I double checked; will change this!

**Comment by smiths** [comment]
Sounds good @samm82.  If it helps, here is an example of a document written using natbib:

https://github.com/smiths/AIMSS/blob/master/StateOfPractice/Methodology/Methodology_arXiv_Version/Methodology.tex

**Comment by JacquesCarette** [comment]
So this still has to be done, right? As what's there is still not 'natbib' yet.

**Pull request closed without merging**
